### ISSUE TITLE
Exception using Rider 2023.2.1

### ISSUE THREAD

**Issue by wertone-gh** [MO2k4/CleanCode#184]
Hello, CleanCode plugin (2023.2) causes exception shown in Rider
`com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable com.jetbrains.rider.plugins.cleancode.options.CleanCodeOptionsPage;
specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: MO.CleanCode-rider]
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:81)
	at com.intellij.openapi.util.NotNullLazyValue$4.compute(NotNullLazyValue.java:120)
	at com.intellij.openapi.util.NotNullLazyValue$4.getValue(NotNullLazyValue.java:105)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:378)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:148)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:94)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.lambda$fetchWeightedElements$4(ActionSearchEverywhereContributor.java:137)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:136)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:184)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:206)
	at com.intellij.codeWithMe.ClientId$Companion.decorateRunnable$lambda$4(ClientId.kt:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)`

This occurs on every Rider launch.

**Comment by MO2k4** [comment]
On which platform do you see this error? I can't directly reproduce on Mac OS

**Comment by gwynnPalmer** [comment]
Hey @MO2k4 I'm also getting this error, which is odd as it was working just fine over the weekend (windows 11).
Interestingly it had been working fine on my work pc which is on windows 10 - I don't know if that is a red herring or not.

**Comment by MO2k4** [comment]
i could reproduce it on windows, i will try to fix this

**Comment by MO2k4** [comment]
Could you check the linked pr and the build and download the artefact and install the plugin manually to verify?

With this version i was not able to reproduce this error

**Comment by melipefello** [comment]
Found the same issue, came here to report. Good to know there's a fix, I will test it.

**Comment by melipefello** [comment]
Getting building version restriction from your azure build
https://dev.azure.com/mo2k4/CleanCode/_build/results?buildId=367&view=results

Rider doesn't let me bump through the ide since it's a patch. I'd need to reinstall or look around to test locally. That will have to wait a bit unfortunately.

**Comment by MO2k4** [comment]
@melipefello u should be able to install it locally without uninstalling it

![image](https://github.com/MO2k4/CleanCode/assets/453360/37f9849e-22c9-485d-addd-9846378268c8)

**Comment by MO2k4** [comment]
The new version will be available soon, hopefully tomorrow
