### ISSUE TITLE
Can not update 5.6.12

### ISSUE THREAD

**Issue by GreenRock** [MO2k4/CleanCode#7]
![image](https://user-images.githubusercontent.com/4007699/71087656-4a7eeb00-21cf-11ea-880d-cf5ec4450e3a.png)
`
Message = “Unable to resolve dependency 'AsyncBridge.Net35 (≥ 0.2.0)'.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
Data.ManagedThreadName = <NULL>
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.Catch(ILogger thіs, Action F, ExceptionOrigin origin, LoggingLevel loggingLevel)
     at JetBrains.UI.SrcView.Extensions.View.ExtensionManagerViewModelProvider.<>c__DisplayClass17_3.<get_Model2>b__24()
     at JetBrains.UI.SrcView.ExtensionManager.ViewModels.ExtensionActionViewModel.Do()
     at JetBrains.UI.SrcView.ExtensionManager.ViewModels.ExtensionManagerViewModel.<BeginInstallation>b__91_0(ProgressIndicator indicator, Property`1 description)
     at JetBrains.UI.SrcView.ExtensionManager.ViewModels.ProgressPage.<>c__DisplayClass18_0.<Run>b__1()
     at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
`
[Kuxuvax.txt](https://github.com/MO2k4/CleanCode/files/3978435/Kuxuvax.txt)

**Comment by MO2k4** [comment]
new version is on its way :-) waiting for jetbrains approval
